=== openbindings/spec/conformance/binding-specs/harness-probes/processor-v7-tls-semantics.manifest.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://openbindings.com/conformance/binding-specs/harness-probes/processor-v7-tls-semantics.manifest.schema.json",
  "title": "AsyncAPI HTTP TLS qualification canonical case manifest",
  "type": "object",
  "required": ["format", "artifact", "caseCount", "acceptedCount", "rejectedCount", "entries"],
  "additionalProperties": false,
  "properties": {
    "format": { "const": "openbindings.asyncapi-http-tls-qualification-manifest@2" },
    "artifact": { "const": "processor-v7-tls-semantics.json" },
    "caseCount": { "type": "integer", "minimum": 1 },
    "acceptedCount": { "type": "integer", "minimum": 1 },
    "rejectedCount": { "type": "integer", "minimum": 1 },
    "entries": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["id", "sha256"],
        "additionalProperties": false,
        "properties": {
          "id": { "type": "string", "pattern": "^C20B-(TLS|SEC|HTTP)-[0-9]{2,}$" },
          "sha256": { "type": "string", "pattern": "^[0-9a-f]{64}$" }
        }
      }
    }
  }
}

=== openbindings/spec/conformance/binding-specs/harness-probes/processor-v7-tls-semantics.manifest.json
{"format":"openbindings.asyncapi-http-tls-qualification-manifest@2","artifact":"processor-v7-tls-semantics.json","caseCount":191,"acceptedCount":43,"rejectedCount":148,"entries":[{"id":"C20B-TLS-01","sha256":"328b3f92c5034fe14a8a4402fc2823b3c5cb39badf9e9bafc429512e146737e1"},{"id":"C20B-TLS-02","sha256":"0f23c8a893e8a1d91e8b52a54c9e40034e29449f5afdaceb90abc3420f8d8f41"},{"id":"C20B-TLS-03","sha256":"839c7ce09eb436d09a11e4f734e76dd25809b2da047e2a17a92f085ae6db724c"},{"id":"C20B-TLS-04","sha256":"a5ff5dfba656d7b8a1f9c4dad1814e81cd4e28690848342055b4ff2c9f1efb5d"},{"id":"C20B-TLS-05","sha256":"cf92a2a87247d9bf0a53f2421b74a8d7374b3681e99f71014d3bbd170ca6d3a9"},{"id":"C20B-TLS-06","sha256":"c20293fdf3788f16a56b22da1e3d362c2a99167a461cf1e4a701ed14ca34e80a"},{"id":"C20B-TLS-07","sha256":"d2d095bff9b7162fff1a339030b7c70a1e3b6b23b097558b4b079c728eb3754c"},{"id":"C20B-TLS-08","sha256":"9df72db55dddf80b259a26c05bc12cfac2a34ad7eece8341dbfcef78e94419d3"},{"id":"C20B-TLS-09","sha256":"407b4cbdfb139924738139cb5abd434e3ffb4de2eb12432d0a6ce0e0de2d2cf3"},{"id":"C20B-TLS-10","sha256":"9b9e5d6dee902349feb687da427a7db180b4437ae5a86d51932f608152cd0a38"},{"id":"C20B-TLS-11","sha256":"b68cc0b7aad7c41a6bdc03498ed45c1c09f918adf83d2dd8cbcec5a10e766932"},{"id":"C20B-TLS-12","sha256":"884517b00ac4f5734d06500a0759656897cba9814ff507f2913f3455dbe2b86e"},{"id":"C20B-TLS-13","sha256":"35580d473e7d17e4477ce80cdb6d24f1526a815f741a4b5f837d07ceb56a3389"},{"id":"C20B-TLS-14","sha256":"c6a31cc497cff8420e4a255f97da6a6d87191e17f331b6ffca0ee5df117ba574"},{"id":"C20B-TLS-15","sha256":"fcfbdcc8114f526d2ffeb5bff6fec2afdcd67975fed3888c24cfffca3acc4db4"},{"id":"C20B-TLS-16","sha256":"a1dc6b477d26b0ddc714a25eea95b5830c67d045300f8f1ed03e2a01e268d720"},{"id":"C20B-TLS-17","sha256":"014fbaf8a86288e9bf592c6271001bf074540ab811c65be3fbc705b740ff41fd"},{"id":"C20B-TLS-18","sha256":"d48a0845fdfa6963d2d066fa64c5fed372b959ce0bfb81c5c884b842a0b07065"},{"id":"C20B-TLS-19","sha256":"ecdba894834004086dbbb0fd377fdcf59761d0ceb1db93103da52f8299debd8d"},{"id":"C20B-TLS-20","sha256":"6a7a204e809a4f4b1cc9c1ad2743bc09c87c4729ab8ca8328e6915ee6d59b6fb"},{"id":"C20B-TLS-21","sha256":"b5b3c9dcf0499f66911fb4762b4ae183bc2da89e5f921790294cd3d9c4afeb39"},{"id":"C20B-TLS-22","sha256":"f051d69318d0a2ec3bd9845e9241d5ec26b52b4f7b4e125ffa2496215e3ceeaa"},{"id":"C20B-TLS-23","sha256":"a8f9a101aa50a214ee0fe82fe724f732179990d34b546304791b8c2301a3f530"},{"id":"C20B-TLS-24","sha256":"da13f930f9b51eca1a4778f065deaced46d78e8f121d987630a7dc4bd4244422"},{"id":"C20B-TLS-25","sha256":"e6cb0abaa57153c512ae025776f896b1b11116ed2f5220cf67afd17a945b8aa1"},{"id":"C20B-TLS-26","sha256":"56446569651de1dc50e7731a8d926f2afc43269003bd7796be15fd1d956ceaf3"},{"id":"C20B-TLS-27","sha256":"6a54da57b9d79ed0d1d06b0ba9e28649c12250162d929487a766a11addb9350d"},{"id":"C20B-TLS-28","sha256":"1274a619b8ce4207823e8a614e163d3d84591f9866f125b7effb083aafe7ed25"},{"id":"C20B-TLS-29","sha256":"aa0543154bdd7793913bdec10a2207033cc9d0d4eccd9e928ac2c7684ac673f1"},{"id":"C20B-TLS-30","sha256":"cef16924aca61471399d4daf7dc6c80186996077366cc44b03229c062c4911f0"},{"id":"C20B-TLS-31","sha256":"949195cec7d5fd1ea4ffe4533ea21f5e08210dd7045e2928262e216c08ee3908"},{"id":"C20B-TLS-32","sha256":"ceb807122d88034063c9f8cfebada366efdba19b719a052a0b4a5000bf9cb9d9"},{"id":"C20B-TLS-33","sha256":"1a8917d861833f69f87ad712721eb89e981ed38dbe488e1d32e7a253dd409043"},{"id":"C20B-TLS-34","sha256":"dcbbae2edacbbf22d3cf59700b37bb217fa7faed7a6a7b900be8e939af9d7d5f"},{"id":"C20B-TLS-35","sha256":"9e7556b0198bdab2a253d82993915c6616e4708713ed28ea4a7ef9e0ed4309bf"},{"id":"C20B-TLS-36","sha256":"a19aa7c7a32f524456f3a8729c0f8c691388acae5eccdb7d8ae08ac29cf3c7e0"},{"id":"C20B-TLS-37","sha256":"87facaa4eb073bbed49b987ea3f0be1a0ea5fd1b4e39502feec1229368b873a3"},{"id":"C20B-TLS-38","sha256":"6563deb7a7a89e35c3ce709f619b3a89fb6ca83d024c81b255ff07048d4c7ae9"},{"id":"C20B-TLS-39","sha256":"14cbd43cc25a339baa1be4ce7d042d4e09252d8c95976986a02a1558d544d56d"},{"id":"C20B-TLS-40","sha256":"4d50f9cf2128544af4d8a22ba3cb0d23ef7745fec47bd8fc7ef0ab4ca66c8f7e"},{"id":"C20B-TLS-41","sha256":"ef3965a7fa38387ddcf328c7b0c459a04bae189d889d0383623765341b8aa4dd"},{"id":"C20B-TLS-42","sha256":"1f334927b2171cb50dc349fb73cc56f796a5bbcf94a1fa34c8e560472f548639"},{"id":"C20B-TLS-43","sha256":"e78cda77f1fe7deb0c530bec5970eedaa5b9fd85e74a9e3aba48802f9c19d34a"},{"id":"C20B-TLS-44","sha256":"e74156a758355f239f022e95e30033ae44393357b35ca3b692236d841e4d21ec"},{"id":"C20B-TLS-45","sha256":"8b0b8276c5cc46f412a6ea95d68cce0853bfe9b5590f00513a357c355c7df806"},{"id":"C20B-TLS-46","sha256":"813a7ac10259af88f9d1368d59f617e7e0cf12555e8c7cdfedf56c34f37f1676"},{"id":"C20B-TLS-47","sha256":"794abc65ea9bba5fe0de89a925924e305231706e974573153a9406773fb136d5"},{"id":"C20B-TLS-48","sha256":"8c4b8a8dc52cb6d1a801f75afbd0b0e03686498703ddaf812c000663155cd6b8"},{"id":"C20B-TLS-49","sha256":"94a4b5a74b83236e11d9b063e6e4d1518042e6cf565a4467b938f2f73d43f577"},{"id":"C20B-TLS-50","sha256":"11f47cbd52ded08b6500fec2d58b5e43fd3854cbb7d302f56118955d19b54f3d"},{"id":"C20B-TLS-51","sha256":"9880191f139e33cfef46c2ea0c022224191a62a0b2eecdd1a90a440555fdb14d"},{"id":"C20B-TLS-52","sha256":"8ccedc024b7d79d45c5dc7a46581fa3287ea387fcc2a51b3945042929e2c7d23"},{"id":"C20B-TLS-53","sha256":"ff46c874013fda6b8eaf0905f93e1d62d2811c0954bfcb5c02a152d9cc7a6346"},{"id":"C20B-TLS-54","sha256":"1d06d4f42a088fc83571eeb620bd89f3c99317cc52b54fe06c2477d2fc7ad5a7"},{"id":"C20B-SEC-01","sha256":"b985c5d09ea98aaf9838aae5a5074f7b1973dae8c109e321ac42353d5553a95e"},{"id":"C20B-SEC-02","sha256":"ff72f545cfd026db3ea167a7f2326fe7e867e69917b1d2f3d89bc1d98f529076"},{"id":"C20B-SEC-03","sha256":"af84f79afbc3e9f401d32441ac1fd75bd3857a0a6019ec0c1322c97c79d71355"},{"id":"C20B-SEC-04","sha256":"d79cf96856095971444a607f2098fa443dbeecf2163ca7805e7aa5b00f3aae73"},{"id":"C20B-SEC-05","sha256":"d41a8ed60b7c178652af35d1f19fcafa1495e4dbaa4764cf4485e68e01d914f2"},{"id":"C20B-SEC-06","sha256":"042c1cc36aea5bbc790662d78ef92c7bdc021787269f576e391ff02dea4c972b"},{"id":"C20B-SEC-07","sha256":"c5e7feab1f9760e80981c8208465b10b856760a2107db84401f06508262dcbdc"},{"id":"C20B-SEC-08","sha256":"59a3af1e36cffe574d13874f62eb7b578321cf36bf114dc10233bef546c59030"},{"id":"C20B-SEC-09","sha256":"b7f93202a4bf6cc987377328ba67f5509ee92bdfa32b6f04c769c697946f0a94"},{"id":"C20B-SEC-10","sha256":"3115821566eba69e4b82fd5f4d49afed7cd2c42b61bb6fc10003b0531c778ac5"},{"id":"C20B-SEC-11","sha256":"1875cca465d08913673dab57e0bc6e36b8427b26296426aeb9234dc567f7eb08"},{"id":"C20B-SEC-12","sha256":"71e30885e0b30fc214207cbd17f0d0702dc483d9379874f9e7d8be011af0ff13"},{"id":"C20B-SEC-13","sha256":"b480f01e78bbf48472921d5fea128423392b69a0a4c66c99cf9948db3611d8e7"},{"id":"C20B-SEC-14","sha256":"8b3f0a6a17483152aa9a3dcaa265a5af0815af9bf3fc28072ef38a395b2d30d9"},{"id":"C20B-SEC-15","sha256":"f48eda3fe9e161054c56cac9045e43abd9f69eeeadd2b07adedc41a16f74897a"},{"id":"C20B-SEC-16","sha256":"8c03a6d55dc0be872c3c44a6f74c9f3c21ad0391172e7046732831a26bcee91f"},{"id":"C20B-SEC-17","sha256":"3970dc7d5dfed24372d9ea071fde280301863cb1c314dc37ec7741623510fe99"},{"id":"C20B-SEC-18","sha256":"903cc5812e19be42b154042a9219652b16a395595f26eada4bae2522b8953f88"},{"id":"C20B-SEC-19","sha256":"df6eef2b0cd4918ecafbd301541ed807698d07a9074b4df6abe834d57890fcbb"},{"id":"C20B-SEC-20","sha256":"10dc6aa507803ae5c445fe236a032204d4ce5aa6848edecb2e7694756d53def6"},{"id":"C20B-SEC-21","sha256":"f674716435b0786fc674aac680325b690c010c877f880194296e7da289a96508"},{"id":"C20B-SEC-22","sha256":"d5f339ae6a1f2e9ee2d4dd8e4fc4ba36e598bbc3fdda2016b6b04c0770fcca85"},{"id":"C20B-SEC-23","sha256":"cf5ead23dde1c3d06e57afbcf88541fb90ce368ee01cec3e3ad229cd7d8b9b25"},{"id":"C20B-SEC-24","sha256":"8816893a95d28c6e44709734ed71b0dfe67cbad0a6dcf0db5bc93b9d7b929351"},{"id":"C20B-SEC-25","sha256":"1bca9fa8ff5b435662f702df21020d4c365a09471d5b8c6e20301c3feddace45"},{"id":"C20B-SEC-26","sha256":"b36a1198bf64a2337224ee315d54fbe9b2b2f5dd3590b9a8f8b8bd169a5fd42c"},{"id":"C20B-SEC-27","sha256":"59e486f922df80c19afb55177aeef82bd067c5474931757bd8b6607310f2fa81"},{"id":"C20B-SEC-28","sha256":"327a68f43f40a4fc83611805b0cfd3f5783c29c71690ec7ce745555cb0801807"},{"id":"C20B-SEC-29","sha256":"084b6441c6e0d4a8a5bcef2966e418bc4249dcfa475600cf48e667da599ea846"},{"id":"C20B-SEC-30","sha256":"15f2f14ed34b4b47a950f6f859fce54ff4ac61d109a8fa3cf11df2fa8a6a44fc"},{"id":"C20B-SEC-31","sha256":"91f6034454a6494a0379978230779c15efec6ca32db00719fa56adcec22e7eb8"},{"id":"C20B-SEC-32","sha256":"22247169c80caa02dc671b6761743c590adf6a21052f5a2d847c4469fec9c54a"},{"id":"C20B-SEC-33","sha256":"2c9b86db3368c26c162b35c5d9a5832f6c12f9198751c0f85ed7a43f0a4e240b"},{"id":"C20B-SEC-34","sha256":"37cc9b1535de3635179d31dc3293468215589c682c7c52f91d6bd629c25695cb"},{"id":"C20B-SEC-35","sha256":"276497acceba577d7a3d1b16e3a2615c9a762a1d3c3fc112d21d9b6935c856ab"},{"id":"C20B-SEC-36","sha256":"2cfd9d7e9a3173af30f760633df0134786983d09776d50b12b2e139cb9b95cc9"},{"id":"C20B-SEC-37","sha256":"6ad84e61b722ff48749581a579a1804d316a59878b8efd31c703151725db25de"},{"id":"C20B-SEC-38","sha256":"e9fed6a7e32fc5ced3ad72c06bbb893297573e881f1eb1daac6deac3086f8ad5"},{"id":"C20B-SEC-39","sha256":"a62522f0d18a8d010e4fbb32229d61f6dec2da027c9bf23288f78a45a45ea08d"},{"id":"C20B-SEC-40","sha256":"08c764643ae2cd42e35380bce280136a2e720f879cfb02e4811d332d62424f7b"},{"id":"C20B-SEC-41","sha256":"53554af9d40c5167f20531e5059731c784d69f2a59cf226b878adebce89b1a2b"},{"id":"C20B-SEC-42","sha256":"6941fee052944cdc74e0bf289347c1b32f96fc6615ed4320d1369c9c5b197a2f"},{"id":"C20B-SEC-43","sha256":"88d22d4adc49be751332044dfd0bbee619d6745bc1d798bafe090cfdf7b0b66d"},{"id":"C20B-SEC-44","sha256":"27b2f8f5dd4b49642e143e2ce4db22441d07a501e18bccb38b5312ba78b96c12"},{"id":"C20B-SEC-45","sha256":"6dbf05d7c52b11f164cf0e65ee471a628afc60458104c9f001f94c7c653ec9df"},{"id":"C20B-SEC-46","sha256":"af706f57e828cc4e2d603370f918c596de5ddf24f42558ee373ee67f366c869a"},{"id":"C20B-SEC-47","sha256":"f6b1b943ef9fd2e36b5213a44920315893f6afd5c902bd489c51503204e5dba2"},{"id":"C20B-SEC-48","sha
